index:
    path: /
    controller: App\Controller\SosteniblesController::index
    
proyectos:
    path: /proyectos
    controller: App\Controller\SosteniblesController::proyectos
    
contacto:
    path: /contacto
    controller: App\Controller\SosteniblesController::contacto

proyecto:
    path: /proyecto/{slug}
    controller: App\Controller\SosteniblesController::proyecto
    
home:
    path: /home/{id_usuario}
    controller: App\Controller\SosteniblesController::home
    
logo:
    path: /logo/{id_proyecto}
    controller: App\Controller\SosteniblesController::logo
    
nuevo_proyecto:
    path: /admin/proyectos/nuevo
    controller: App\Controller\AdminController::nuevo