index:
    path: /
    controller: App\Controller\SosteniblesController::index
    
proyectos:
    path: /proyectos
    controller: App\Controller\SosteniblesController::proyectos
    
contacto:
    path: /contacto
    controller: App\Controller\SosteniblesController::contacto

proyecto:
    path: /proyecto/{slug}
    controller: App\Controller\SosteniblesController::proyecto

nuevo_proyecto:
    path: /admin/proyectos/nuevo
    controller: App\Controller\AdminController::nuevo

home:
    path: /admin/home/{id}
    controller: App\Controller\AdminController::home

logo:
    path: /admin/logo/{id}
    controller: App\Controller\AdminController::logo

security_login:
    path: /login
    controller: App\Controller\AdminController::login

security_logout:
    path: /logout
    controller: App\Controller\AdminController::logout

user_registration:
    path: /register
    controller: App\Controller\AdminController::register