<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X_radeb' shared service.

return $this->privates['.service_locator.X_radeb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('paginator' => function () {
    return ($this->services['knp_paginator'] ?? $this->load('getKnpPaginatorService.php'));
}, 'repository' => function (): \App\Repository\ProyectosRepository {
    return ($this->privates['App\Repository\ProyectosRepository'] ?? $this->load('getProyectosRepositoryService.php'));
}));
