<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController::home' => function () {
    return ($this->privates['.service_locator.bsrG56g'] ?? $this->load('get_ServiceLocator_BsrG56gService.php'));
}, 'App\\Controller\\AdminController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\AdminController::logo' => function () {
    return ($this->privates['.service_locator.lkxNnKE'] ?? $this->load('get_ServiceLocator_LkxNnKEService.php'));
}, 'App\\Controller\\AdminController::register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SosteniblesController::proyecto' => function () {
    return ($this->privates['.service_locator.lkxNnKE'] ?? $this->load('get_ServiceLocator_LkxNnKEService.php'));
}, 'App\\Controller\\SosteniblesController::proyectos' => function () {
    return ($this->privates['.service_locator.X_radeb'] ?? $this->load('get_ServiceLocator_XRadebService.php'));
}, 'App\\Controller\\AdminController:home' => function () {
    return ($this->privates['.service_locator.bsrG56g'] ?? $this->load('get_ServiceLocator_BsrG56gService.php'));
}, 'App\\Controller\\AdminController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\AdminController:logo' => function () {
    return ($this->privates['.service_locator.lkxNnKE'] ?? $this->load('get_ServiceLocator_LkxNnKEService.php'));
}, 'App\\Controller\\AdminController:register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SosteniblesController:proyecto' => function () {
    return ($this->privates['.service_locator.lkxNnKE'] ?? $this->load('get_ServiceLocator_LkxNnKEService.php'));
}, 'App\\Controller\\SosteniblesController:proyectos' => function () {
    return ($this->privates['.service_locator.X_radeb'] ?? $this->load('get_ServiceLocator_XRadebService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
