<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.bsrG56g.App\Entity\Usuarios' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.bsrG56g": it references class "App\\Entity\\Usuarios" but no such service exists.');
