<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMRVguj7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMRVguj7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMRVguj7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMRVguj7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMRVguj7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MRVguj7',
    'container.build_id' => '933735e7',
    'container.build_time' => 1537304089,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMRVguj7');
