<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUMiZzn1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUMiZzn1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUMiZzn1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUMiZzn1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUMiZzn1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UMiZzn1',
    'container.build_id' => '96152081',
    'container.build_time' => 1537898961,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUMiZzn1');
