<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnUBjjI\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnUBjjI/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKnUBjjI.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKnUBjjI\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKnUBjjI\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KnUBjjI',
    'container.build_id' => 'd4ecd7c7',
    'container.build_time' => 1538160399,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnUBjjI');
