<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bsrG56g' shared service.

return $this->privates['.service_locator.bsrG56g'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('usuario' => function (): \App\Entity\Usuarios {
    return ($this->privates['.errored..service_locator.bsrG56g.App\Entity\Usuarios'] ?? $this->load('getUsuariosService.php'));
}));
