<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lkxNnKE' shared service.

return $this->privates['.service_locator.lkxNnKE'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('proyecto' => function (): \App\Entity\Proyectos {
    return ($this->privates['.errored..service_locator.lkxNnKE.App\Entity\Proyectos'] ?? $this->load('getProyectosService.php'));
}));
